### ISSUE TITLE
in node.js 0.11.X can't install

### ISSUE THREAD

**Issue by c941010623** [bnoordhuis/node-iconv#105]

**Comment by bnoordhuis** [comment]
Um, can you maybe provide some details?

**Comment by c941010623** [comment]
use npm install than will see the error

i use io.js  and node.js 0.11.X (NEW)

they will not npm install have error

but node.js 0.10.35 is OK

**Comment by bnoordhuis** [comment]
I fixed that yesterday in 08e13c9.  If you upgrade to v2.1.5, it should work with io.js and node.js v0.11.14.  I won't vouch for v0.11.15 just yet, that may require one or two fixes to nan.
