### ISSUE TITLE
Error with npm install on Windows 8

### ISSUE THREAD

**Issue by joeeames** [bnoordhuis/node-iconv#111]
I can clone the repo, and if I manually "npm install nan" then "node-gyp rebuild" I have no problems. The Release pdb, lib, etc are all created just fine. But from within the cloned directory, if I simply try to "npm install" I get the following npm-debug log:

note: the error the console gives me lists a path to my python that isn't the same as is specified in my environment variables. for some reason a different path to python has been cached somewhere and is being used. I don't know if that is relevant.

0 info it worked if it ends with ok
1 verbose cli [ 'c:\\nodist\\bin\\\\node.exe',
1 verbose cli   'c:\\nodist\\bin\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.1.16
3 info using node@v0.12.0
4 verbose node symlink c:\nodist\bin\\node.exe
5 verbose install where, deps [ 'C:\\dev\\tmp\\node-iconv', [ 'nan', 'tap' ] ]
6 verbose install where, peers [ 'C:\\dev\\tmp\\node-iconv', [] ]
7 info preinstall iconv@2.1.6
8 verbose already installed skipping nan@~1.6.2 C:\dev\tmp\node-iconv
9 verbose already installed skipping tap@~0.4.8 C:\dev\tmp\node-iconv
10 silly install resolved []
11 info build C:\dev\tmp\node-iconv
12 verbose linkStuff [ false, false, false, 'C:\\dev\\tmp' ]
13 info linkStuff iconv@2.1.6
14 verbose linkBins iconv@2.1.6
15 verbose linkMans iconv@2.1.6
16 verbose rebuildBundles iconv@2.1.6
17 verbose rebuildBundles [ '.bin', 'nan', 'tap' ]
18 info install iconv@2.1.6
19 verbose unsafe-perm in lifecycle true
20 info iconv@2.1.6 Failed to exec install script
21 verbose stack Error: iconv@2.1.6 install: `node-gyp rebuild`
21 verbose stack Exit status 1
21 verbose stack     at EventEmitter.<anonymous> (c:\nodist\bin\node_modules\npm\lib\utils\lifecycle.js:212:16)
21 verbose stack     at EventEmitter.emit (events.js:110:17)
21 verbose stack     at ChildProcess.<anonymous> (c:\nodist\bin\node_modules\npm\lib\utils\spawn.js:14:12)
21 verbose stack     at ChildProcess.emit (events.js:110:17)
21 verbose stack     at maybeClose (child_process.js:1008:16)
21 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
22 verbose pkgid iconv@2.1.6
23 verbose cwd C:\dev\tmp\node-iconv
24 error Windows_NT 6.3.9600
25 error argv "c:\\nodist\\bin\\\\node.exe" "c:\\nodist\\bin\\node_modules\\npm\\bin\\npm-cli.js" "install"
26 error node v0.12.0
27 error npm  v2.1.16
28 error code ELIFECYCLE
29 error iconv@2.1.6 install: `node-gyp rebuild`
29 error Exit status 1
30 error Failed at the iconv@2.1.6 install script 'node-gyp rebuild'.
30 error This is most likely a problem with the iconv package,
30 error not with npm itself.
30 error Tell the author that this fails on your system:
30 error     node-gyp rebuild
30 error You can get their info via:
30 error     npm owner ls iconv
30 error There is likely additional logging output above.
31 verbose exit [ 1, true ]

**Comment by bnoordhuis** [comment]
I don't know, honestly.  npm is being pretty obtuse here: it says `node-gyp rebuild` failed but it doesn't say why.

#110 is another report from a Windows 8 user.  Are there any commonalities?

**Comment by 29Esther** [comment]
I also failed to build it under Window 7

**Comment by yunchiri** [comment]
I also failed to build it under Window 7 too

**Comment by bnoordhuis** [comment]
Do you get the exact same error?  What happens when you run `node-gyp rebuild`?

**Comment by halfcrazy** [comment]
install failed on win7 too.

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.t
argets(64,5): error MSB8020: The build tools for Visual Studio 2012 (Platform T
oolset = 'v110') cannot be found. To build using the v110 build tools, please i
nstall Visual Studio 2012 build tools.  Alternatively, you may upgrade to the c
urrent Visual Studio tools by selecting the Project menu or right-click the sol
ution, and then selecting "Upgrade Solution...". [C:\Users\Sylar\Desktop\cr\2\n
ode_modules\iconv\build\libiconv.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Development\nodejs\node_modules\np
m\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:
12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "D:\\Development\\nodejs\\node_modules\\npm\\node_module
s\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Sylar\Desktop\cr\2\node_modules\iconv
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by jcollum** [comment]
Same here. Relevant lines: 

```
668 verbose stack Error: iconv@2.1.8 install: `node-gyp rebuild`
668 verbose stack Exit status 1
668 verbose stack     at EventEmitter.<anonymous> (c:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
668 verbose stack     at EventEmitter.emit (events.js:110:17)
668 verbose stack     at ChildProcess.<anonymous> (c:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
668 verbose stack     at ChildProcess.emit (events.js:110:17)
668 verbose stack     at maybeClose (child_process.js:1015:16)
668 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
669 verbose pkgid iconv@2.1.8
670 verbose cwd c:\projects\serd\alpha_beta
671 error Windows_NT 6.3.9600
672 error argv "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "iconv@2.1.8"
673 error node v0.12.7
674 error npm  v2.11.3
675 error code ELIFECYCLE
676 error iconv@2.1.8 install: `node-gyp rebuild`
676 error Exit status 1
677 error Failed at the iconv@2.1.8 install script 'node-gyp rebuild'.
```

I told them I'd take a shot at building my project on Windows. Shot taken, it failed, no problem, I'll install a saner OS on that machine now.

**Comment by jcollum** [comment]
Seems that I solved it. This post was helpful: http://stackoverflow.com/a/21366601/30946 

Short answer: install VS 2012 Express, re-try to install node-iconv.
