### ISSUE TITLE
Issues installing in Debian 8

### ISSUE THREAD

**Issue by Jzarecta** [bnoordhuis/node-iconv#115]
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp

I wonder if there is some dependency or permission I should be using through the compiling.
I only put 
```bash
$ npm install inconv
```
Using node -v v0.10.29, node-gyp -v v0.12.2

**Comment by bnoordhuis** [comment]
Can you post the contents of npm-debug.log?

Out of curiosity, why are you running v0.10.29?  You're missing out on a number of moderately critical security fixes.

**Comment by Jzarecta** [comment]
I solved it, the issue was node-legacy package and node binary (or softlink) was not found on the box. Probably a bug since nodejs is usually the binary name now on most linux distros. A conditional function that can switch to nodejs instead of a statical node binary on the shell script might fix this.

**Comment by bnoordhuis** [comment]
I'm pretty sure it's only the debian derivatives that rename the binary and I have no intention of catering to that.  Anyway, I'm glad you resolved it.
