### ISSUE TITLE
Error installing on Ubuntu 14.04

### ISSUE THREAD

**Issue by colinmollenhour** [bnoordhuis/node-iconv#117]
After a clean install of npm on Ubuntu 14.04 I tried to install Haraka and recevied the following error:

```
> iconv@2.1.7 install /usr/local/lib/node_modules/Haraka/node_modules/iconv
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-27-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/Haraka/node_modules/iconv
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! weird error 1
npm ERR! not ok code 0
```

Apparently Ubuntu has only a `nodejs` binary and no `node` binary. I created a symlink `/usr/bin/node -> /usr/bin/nodejs` and that fixed the issue but it would be better if this worked out of the box.

**Comment by bnoordhuis** [comment]
It's because Debian (Ubuntu's upstream) decided to rename the binary.  I'm not going to try working around that because just about every script and add-on depends on there being a node or iojs binary on the path somewhere; node-iconv is not unique in that regard.

Just install the nodejs-legacy package (better yet, the PPA) or create a symlink manually, like you did.

**Comment by colinmollenhour** [comment]
Ok. I didn't ready about nodejs-legacy.. For what it's worth Haraka has a *lot* of other dependencies besides iconv and none of them had this issue. Perhaps just a note in the README or an error message which mentions nodejs-legacy? If I submit a PR with a minor README update will you consider it?

**Comment by bnoordhuis** [comment]
> For what it's worth Haraka has a lot of other dependencies besides iconv and none of them had this issue.

Modules that use nan (an io.js and node.js version compatibility layer) use that exact same stanza and many modules use nan.  You're bound to hit it sooner or later.

> Perhaps just a note in the README or an error message which mentions nodejs-legacy? If I submit a PR with a minor README update will you consider it?

Thanks but no.  Debian made their bed, now they should lie in it.  Hopefully, if enough people get mad, they'll change their policy.
