### ISSUE TITLE
Can't install on Windows 8

### ISSUE THREAD

**Issue by angelmunozs** [bnoordhuis/node-iconv#119]
When I try to do __npm install iconv__, I get the following error (translated from Spanish):

>'C:\Users\Ángel\Scripts\node_modules\iconv\build\libiconv.vcxproj(39,46): error MSB4025: Could not load project file. Invalid character in coding provided. Line 39, column 46'

I think it may be because of the folder name, containing an 'Á'. Any idea of how I can fix this?

Thanks!

**Comment by bnoordhuis** [comment]
Hi @angelmunozs, sorry for the delay.  Yes, I speculate it's because of the diacritic in the path; I think you've hit https://github.com/TooTallNate/node-gyp/issues/297 (node-gyp is the build system for native modules.)
