### ISSUE TITLE
npm install doesn't work

### ISSUE THREAD

**Issue by universeOS** [bnoordhuis/node-iconv#121]
npm ERR! error installing iconv@1.2.4

npm ERR! iconv@1.2.4 preinstall: `node-waf clean || (exit 0); node-waf configure build`
npm ERR! `sh "-c" "node-waf clean || (exit 0); node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the iconv@1.2.4 preinstall script.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf clean || (exit 0); node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 2.6.32-042stab092.3
npm ERR! command "node" "/usr/bin/npm" "install" "iconv"
npm ERR! cwd /var/www/vhosts/transparency-everywhere.com/httpdocs/newsbomb
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! code ELIFECYCLE
npm ERR! message iconv@1.2.4 preinstall: `node-waf clean || (exit 0); node-waf configure build`
npm ERR! message `sh "-c" "node-waf clean || (exit 0); node-waf configure build"` failed with 1
npm ERR! errno {}

**Comment by bnoordhuis** [comment]
I recently removed the wscript file.  Why are you still using node.js v0.6?  It's been unsupported for years.

**Comment by universeOS** [comment]
sorry I copied the wrong lines. I just installed it and forgot to uptaded it some lines below. The error I wanted to report is this one:


npm WARN using --force I sure hope you know what you are doing.
npm WARN package.json newsbomb@0.0.0 No description
npm WARN package.json newsbomb@0.0.0 No README data
npm WARN package.json newsbomb@0.0.0 No license field.
\
> iconv@2.1.8 install /var/www/vhosts/transparency-everywhere.com/httpdocs/newsbomb/node_modules/iconv
> node-gyp rebuild

make: Gehe in Verzeichnis '/var/www/vhosts/transparency-everywhere.com/httpdocs/newsbomb/node_modules/iconv/build'
  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
  AR(target) Release/obj.target/iconv.a
  COPY Release/iconv.a
  CXX(target) Release/obj.target/iconv/src/binding.o
make: g++: Kommando nicht gefunden
make: *** [Release/obj.target/iconv/src/binding.o] Fehler 127
make: Verlasse Verzeichnis '/var/www/vhosts/transparency-everywhere.com/httpdocs/newsbomb/node_modules/iconv/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 2.6.32-042stab092.3
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/vhosts/transparency-everywhere.com/httpdocs/newsbomb/node_modules/iconv
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok

**Comment by bnoordhuis** [comment]
> make: g++: Kommando nicht gefunden

Installing g++ should fix that.

**Comment by universeOS** [comment]
you are right, it does! thanks :)
