### ISSUE TITLE
catching EINVAL error

### ISSUE THREAD

**Issue by rashthedude** [bnoordhuis/node-iconv#122]
Since 'EINVAL' is apparently a feature rather than a bug is there a way to catch it if it's being encountered?

**Comment by bnoordhuis** [comment]
Sorry, looks like I never got a notification for this issue.  When you say 'catch it', I assume you don't mean catch the exception but suppress it somehow?

If you're converting whole inputs, you can chop off bytes and retry until it doesn't error anymore.  If you're converting chunk-by-chunk, there is no general solution but the easiest workaround is to simply never call `stream.end()` - the EINVAL is only emitted when the final chunk ends in an incomplete sequence.
