### ISSUE TITLE
node-iconv is using nan 2.0.4 which hasn't been properly published to npm

### ISSUE THREAD

**Issue by Abarrowman** [bnoordhuis/node-iconv#125]
Installing iconv is failing.
Seems to be related to https://github.com/nodejs/nan/issues/405

**Comment by bnoordhuis** [comment]
WFM, downloads and builds fine.  Maybe a problem with npm or something in between you and npm's servers?

**Comment by Abarrowman** [comment]
You're right it looks like an issue with Sonatype Nexus, sorry for the alarm.
