### ISSUE TITLE
Bug fix release 2.1.9 removed support for node version >0.10.36

### ISSUE THREAD

**Issue by tomowens3** [bnoordhuis/node-iconv#128]
Have a client that is using a old version of node (v0.10.36) and the app's package.json has its iconv dependency set to "~2.1.4". Setting the version to exactly match "2.1.8" fixed the build error.

BTW the error was:
```
In file included from ../src/binding.cc:18:
../node_modules/nan/nan.h:318: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
```
Recommend bumping up the minor version.

**Comment by bnoordhuis** [comment]
Thanks for the suggestion but I don't want to bump minor for a bug fix in a dependency.
