### ISSUE TITLE
cannot install `iconv` on Travis CI for io.js or Node 4.0.x

### ISSUE THREAD

**Issue by Mithgol** [bnoordhuis/node-iconv#132]
On [Travis CI](https://travis-ci.org/) I've encountered a failure when I tried to install `iconv` for io.js ([see a job log](https://travis-ci.org/ashtuchkin/iconv-lite/jobs/79717321)) or for Node.js v4.0.0 ([see a job log](https://travis-ci.org/ashtuchkin/iconv-lite/jobs/79717322)), though everything was fine for older versions of Node (0.8, 0.10, 0.11, 0.12).

**Comment by bnoordhuis** [comment]
That build failure is unrelated to iconv, you need a C++11-capable compiler for io.js v3 and node v4.  Install g++ 4.8 or clang++ 3.4 or newer and you should be good to go.

**Comment by Mithgol** [comment]
Thanks, the problem is gone.
