### ISSUE TITLE
Iconv can't be installed in win7

### ISSUE THREAD

**Issue by sharh** [bnoordhuis/node-iconv#134]
The install error message:

gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\AppCan\AppCanStudioPersonalV3.2\HDK\emulator\mas\nod
e_modules\npm\node_modules\node-gyp\lib\configure.js:337:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "D:\\AppCan\\AppCanStudioPersonalV3.2\\HDK\\emulator\\mas\\node_modules\\npm
\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\newFile_1015\IBM_Cloud\sharhhu (1)\node_modules\iconv
gyp ERR! node -v v0.10.15
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm ERR! iconv@2.1.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.1.11 install script.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "D:\\AppCan\\AppCanStudioPersonalV3.2\\HDK\\emulator\\mas\\\\node.exe" "D:\\AppCan\
\AppCanStudioPersonalV3.2\\HDK\\emulator\\mas\\node_modules\\npm\\bin\\npm-cli.js" "install" "iconv"
 "--save"
npm ERR! cwd D:\newFile_1015\IBM_Cloud\sharhhu (1)
npm ERR! node -v v0.10.15
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\newFile_1015\IBM_Cloud\sharhhu (1)\npm-debug.log
npm ERR! not ok code 0

**Comment by bnoordhuis** [comment]
Can you post the full output starting from `npm install iconv`?  Please include the contents of npm-debug.log as well.

**Comment by TLR12** [comment]
Hi I've attached the npm-debug log you've requested see the attachment

[npm-debug.txt](https://github.com/bnoordhuis/node-iconv/files/44990/npm-debug.txt)

**Comment by bnoordhuis** [comment]
@TLR12 Thanks.  npm didn't include the actual error, it looks like.  What happens when you clone the repo and run `node-gyp rebuild`?

**Comment by TLR12** [comment]
@bnoordhuis I think the problem comes from the fact that I'm compiling it with visual studio 2015 instead of 2013, however I don't get the problem when I try to build it under a nodejs version that is smaller than version 4. Any thoughts?

**Comment by bnoordhuis** [comment]
VS 2013 and 2015 should both work.  Can you post the build error?

**Comment by TLR12** [comment]
[buildlog.txt](https://github.com/bnoordhuis/node-iconv/files/45664/buildlog.txt)

**Comment by bnoordhuis** [comment]
I think you're running into an issue with a SDK that you have installed because it doesn't look related to node-iconv.  The salient bits:
```
2>  binding.cc
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\corecrt_terminate.h(34): error C2872: 'terminate_handler': ambiguous symbol
2>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\corecrt_terminate.h(19): note: could be 'void (__cdecl *__cdecl terminate_handler)(void)'
2>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\exception(191): note: or       'std::terminate_handler'
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\corecrt_terminate.h(35): error C2872: 'terminate_handler': ambiguous symbol
2>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\corecrt_terminate.h(19): note: could be 'void (__cdecl *__cdecl terminate_handler)(void)'
2>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\exception(191): note: or       'std::terminate_handler'
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\corecrt_terminate.h(38): error C2872: 'terminate_handler': ambiguous symbol
2>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\corecrt_terminate.h(19): note: could be 'void (__cdecl *__cdecl terminate_handler)(void)'
2>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\exception(191): note: or       'std::terminate_handler'
2>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\eh.h(35): error C2872: 'unexpected_handler': ambiguous symbol
2>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\eh.h(19): note: could be 'void (__cdecl *__cdecl unexpected_handler)(void)'
2>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\exception(192): note: or       'std::unexpected_handler'
2>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\eh.h(36): error C2872: 'unexpected_handler': ambiguous symbol
2>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\eh.h(19): note: could be 'void (__cdecl *__cdecl unexpected_handler)(void)'
2>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\exception(192): note: or       'std::unexpected_handler'
2>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\eh.h(39): error C2872: 'unexpected_handler': ambiguous symbol
2>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\eh.h(19): note: could be 'void (__cdecl *__cdecl unexpected_handler)(void)'
2>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\exception(192): note: or       'std::unexpected_handler'
```

**Comment by bnoordhuis** [comment]
No follow-up.  I'll go ahead and assume this is working now.  Closing.

**Comment by paulcbetts** [comment]
Since this is literally the only mention on the Internet of my problem, this seems to be related to nan + VS2015 (https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/), and building node-gyp modules with VS2015 as your compiler (I'm seeing it right now on  https://github.com/dachev/node-cld).

@bnoordhuis If you've got any super Pro Tips on how to fix this, I'm all ears, otherwise I'll keep digging

**Comment by bnoordhuis** [comment]
@paulcbetts I'm afraid I never figured it out but I suspect something (not node-iconv) is doing `using namespace xxx` somewhere, probably `using namespace std`, or maybe `using std::terminate_handler` in the global namespace.

**Comment by paulcbetts** [comment]
@bnoordhuis It's definitely something lower than that, a grep through `nan` didn't reveal any smoking guns though. I'll keep digging, thanks for the tip.
