### ISSUE TITLE
iconv@2.1.11 install failed

### ISSUE THREAD

**Issue by jShi-git** [bnoordhuis/node-iconv#135]
centos 6.3
```
npm ERR! Linux 2.6.32-358.6.2.el6.x86_64
...
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
...
npm ERR! Failed at the iconv@2.1.11 install script 'node-gyp rebuild'.
```

the npm-debug.log

http://www.heypasteit.com/clip/29TZ

**Comment by bnoordhuis** [comment]
Not a problem with node-iconv.  Those compiler errors mean your compiler is too old to understand C++11 (which you need for node.js v4.x+.)  Upgrade to at least g++ 4.8.2 or clang++ 3.4.
