### ISSUE TITLE
Can not install iconv on node 4.2.2  

### ISSUE THREAD

**Issue by andrydl** [bnoordhuis/node-iconv#136]
Hello. I can not install iconv . I try 
npm install iconv
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
npm WARN package.json @ No license field.
/
> iconv@2.1.11 install /usr/pg-monitor/node_modules/iconv
> node-gyp rebuild

sh: node-gyp: command not found (translate from russian)
npm ERR! Linux 2.6.32-431.el6.x86_64
npm ERR! argv "/root/.nvm/versions/node/v4.2.2/bin/node" "/root/.nvm/versions/node/v4.2.2/bin/npm" "install" "iconv"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! iconv@2.1.11 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the iconv@2.1.11 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

**Comment by bnoordhuis** [comment]
> sh: node-gyp: command not found

That suggests your npm install is broken because node-gyp is normally shipped with npm.

**Comment by andrydl** [comment]
Anothe modules installing, except iconv. I installed gcc version 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC) , but iconv don't installed. Under CentOS 7 , install it, but   under 6.7 not. Node 4.2.2 installing by nvm

**Comment by bnoordhuis** [comment]
What happens when you `npm install buffertools` or `npm install heapdump`?

**Comment by andrydl** [comment]
I 'm  installed node 4.2.2 from nvm. After installation node-gyp ,I install
iconv.  CentOS 6 do not have package with new node 4.2.2.
.

2015-11-16 15:21 GMT+03:00 Ben Noordhuis <notifications@github.com>:

**Comment by bnoordhuis** [comment]
It's probably in the node-devel package.  Glad to hear it's solved though.
