### ISSUE TITLE
Problems while using with node 5.*.* 

### ISSUE THREAD

**Issue by maxpolski** [bnoordhuis/node-iconv#142]

**Comment by maxpolski** [comment]
Error: Cannot find module '../build/Debug/iconv.node'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

**Comment by bnoordhuis** [comment]
Can you post the output of `npm install iconv`?  Please include the contents of npm-debug.log.

**Comment by maxpolski** [comment]
yes, sure thing 

0 info it worked if it ends with ok
1 verbose cli [ '/home/username/.nvm/versions/node/v5.0.0/bin/node',
1 verbose cli   '/home/username/.nvm/versions/node/v5.0.0/bin/npm',
1 verbose cli   'i' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly loadAllDepsIntoIdealTree Finishing
20 silly idealTree:prePrune iconv@2.0.7
21 silly loadIdealTree Finishing
22 silly currentTree iconv@2.0.7
23 silly idealTree iconv@2.0.7
24 silly generateActionsToTake Starting
25 silly install generateActionsToTake
26 silly generateActionsToTake Finishing
27 silly diffTrees action count 0
28 silly decomposeActions action count 0
29 silly executeActions Starting
30 silly install executeActions
31 silly doSerial global-install 0
32 silly doParallel fetch 0
33 verbose lock using /home/username/.npm/_locks/staging-66757b865e1869a6.lock for /home/username/development/project_name/node_modules/iconv/node_modules/.staging
34 silly doParallel extract 0
35 silly doParallel preinstall 0
36 silly doReverseSerial remove 0
37 silly doSerial move 0
38 silly doSerial finalize 0
39 silly doSerial build 0
40 silly doSerial global-link 0
41 silly doParallel update-linked 0
42 silly doSerial install 0
43 silly doSerial postinstall 0
44 verbose unlock done using /home/username/.npm/_locks/staging-66757b865e1869a6.lock for //home/username/development/project_name/node_modules/iconv/node_modules/.staging
45 silly executeActions Finishing
46 silly rollbackFailedOptional Starting
47 silly rollbackFailedOptional Finishing
48 silly runTopLevelLifecycles Starting
49 silly install runTopLevelLifecycles
50 silly preinstall iconv /home/username/development/project_name.node_modules/iconv/iconv-1d1713c6d2aaa53727ca3f32dcc4cf6c
51 info lifecycle iconv@2.0.7~preinstall: iconv@2.0.7
52 silly lifecycle iconv@2.0.7~preinstall: no script for preinstall, continuing
53 silly build iconv
54 info linkStuff iconv@2.0.7
55 silly linkStuff iconv@2.0.7 has /home/username/development/project_name/node_modules as its parent node_modules
56 verbose linkBins iconv@2.0.7
57 verbose linkMans iconv@2.0.7
58 verbose rebuildBundles iconv@2.0.7
59 verbose rebuildBundles []
60 silly install iconv /home/username/development/project_name/node_modules/iconv/iconv-1d1713c6d2aaa53727ca3f32dcc4cf6c
61 info lifecycle iconv@2.0.7~install: iconv@2.0.7
62 verbose lifecycle iconv@2.0.7~install: unsafe-perm in lifecycle true
63 verbose lifecycle iconv@2.0.7~install: PATH: /home/username/.nvm/versions/node/v5.0.0/lib/node_modules/npm/bin/node-gyp-bin://home/username/development/project_name/node_modules/iconv/node_modules/
64 verbose lifecycle iconv@2.0.7~install: CWD: /home/username/development/project_name/node_modules/iconv
65 silly lifecycle iconv@2.0.7~install: Args: [ '-c', 'node-gyp rebuild' ]
66 silly lifecycle iconv@2.0.7~install: Returned: code: 1  signal: null
67 info lifecycle iconv@2.0.7~install: Failed to exec install script
68 verbose stack Error: iconv@2.0.7 install: `node-gyp rebuild`
68 verbose stack Exit status 1
68 verbose stack     at EventEmitter.<anonymous> (/home/username/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/utils/lifecycle.js:233:16)
68 verbose stack     at emitTwo (events.js:87:13)
68 verbose stack     at EventEmitter.emit (events.js:172:7)
68 verbose stack     at ChildProcess.<anonymous> (/home/username/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
68 verbose stack     at emitTwo (events.js:87:13)
68 verbose stack     at ChildProcess.emit (events.js:172:7)
68 verbose stack     at maybeClose (internal/child_process.js:818:16)
68 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
69 verbose pkgid iconv@2.0.7
70 verbose cwd /home/username/development/project_name/node_modules/iconv
71 error Linux 3.13.0-24-generic
72 error argv "/home/username/.nvm/versions/node/v5.0.0/bin/node" "/home/username/.nvm/versions/node/v5.0.0/bin/npm" "i"
73 error node v5.0.0
74 error npm  v3.3.6
75 error code ELIFECYCLE
76 error iconv@2.0.7 install: `node-gyp rebuild`
76 error Exit status 1
77 error Failed at the iconv@2.0.7 install script 'node-gyp rebuild'.
77 error This is most likely a problem with the iconv package,
77 error not with npm itself.
77 error Tell the author that this fails on your system:
77 error     node-gyp rebuild
77 error You can get their info via:
77 error     npm owner ls iconv
77 error There is likely additional logging output above.
78 verbose exit [ 1, true ]

I've forgot to add one more thing: I'm installing iconv by cloning it from github, and I take this error, when I make npm install in "node-iconv" directory

**Comment by bnoordhuis** [comment]
The issue seems to be with `node-gyp rebuild` but npm is being its regular obtuse self again and hides the error.  Can you try running `node-gyp rebuild` manually?

**Comment by maxpolski** [comment]
gyp info ok 
But still got same error

**Comment by bnoordhuis** [comment]
You mean `node-gyp rebuild` works when invoked directly?, just not when called from npm?  If that's the case I don't know what the issue is but it's probably not caused by node-iconv itself.

**Comment by maxpolski** [comment]
Ok, thanks for answer.
