### ISSUE TITLE
Can't build for 32bit architecture

### ISSUE THREAD

**Issue by KristjanTammekivi** [bnoordhuis/node-iconv#143]
I'm unable to build for 32 bit systems, on the same system I can still build without specifying arch.

System: Ubuntu 15.10
Same problem on my Debian 7 build server

	➜  node-iconv git:(master) node-gyp rebuild --arch=ia32
	gyp info it worked if it ends with ok
	gyp info using node-gyp@3.2.1
	gyp info using node@4.2.3 | linux | x64
	gyp info spawn /usr/bin/python2
	gyp info spawn args [ '/home/kristjan/npm/lib/node_modules/node-gyp/gyp/gyp_main.py',
	gyp info spawn args   'binding.gyp',
	gyp info spawn args   '-f',
	gyp info spawn args   'make',
	gyp info spawn args   '-I',
	gyp info spawn args   '/home/kristjan/projects/node-iconv/build/config.gypi',
	gyp info spawn args   '-I',
	gyp info spawn args   '/home/kristjan/npm/lib/node_modules/node-gyp/addon.gypi',
	gyp info spawn args   '-I',
	gyp info spawn args   '/home/kristjan/.node-gyp/4.2.3/include/node/common.gypi',
	gyp info spawn args   '-Dlibrary=shared_library',
	gyp info spawn args   '-Dvisibility=default',
	gyp info spawn args   '-Dnode_root_dir=/home/kristjan/.node-gyp/4.2.3',
	gyp info spawn args   '-Dnode_gyp_dir=/home/kristjan/npm/lib/node_modules/node-gyp',
	gyp info spawn args   '-Dnode_lib_file=node.lib',
	gyp info spawn args   '-Dmodule_root_dir=/home/kristjan/projects/node-iconv',
	gyp info spawn args   '--depth=.',
	gyp info spawn args   '--no-parallel',
	gyp info spawn args   '--generator-output',
	gyp info spawn args   'build',
	gyp info spawn args   '-Goutput_dir=.' ]
	gyp info spawn make
	gypmake: Entering directory '/home/kristjan/projects/node-iconv/build'
	 info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
	  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
	  AR(target) Release/obj.target/iconv.a
	  COPY Release/iconv.a
	  CXX(target) Release/obj.target/iconv/src/binding.o
	In file included from /usr/include/c++/5/algorithm:60:0,
	                 from ../node_modules/nan/nan.h:28,
	                 from ../src/binding.cc:18:
	/usr/include/c++/5/utility:68:28: fatal error: bits/c++config.h: No such file or directory
	compilation terminated.
	iconv.target.mk:103: recipe for target 'Release/obj.target/iconv/src/binding.o' failed
	make: *** [Release/obj.target/iconv/src/binding.o] Error 1
	make: Leaving directory '/home/kristjan/projects/node-iconv/build'
	gyp ERR! build error 
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/home/kristjan/npm/lib/node_modules/node-gyp/lib/build.js:276:23)
	gyp ERR! stack     at emitTwo (events.js:87:13)
	gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
	gyp ERR! System Linux 4.2.0-23-generic
	gyp ERR! command "/usr/local/bin/node" "/home/kristjan/npm/bin/node-gyp" "rebuild" "--arch=ia32"
	gyp ERR! cwd /home/kristjan/projects/node-iconv
	gyp ERR! node -v v4.2.3
	gyp ERR! node-gyp -v v3.2.1
	gyp ERR! not ok

**Comment by bnoordhuis** [comment]
> /usr/include/c++/5/utility:68:28: fatal error: bits/c++config.h: No such file or directory

Local problem.  I can't tell what distro you're using but you probably need to install libc++-dev or similar named package.

**Comment by bnoordhuis** [comment]
No follow-up.  I'll go ahead and assume this is working now.  Closing.
