### ISSUE TITLE
latin1 to utf8 with implicit buffer conversions

### ISSUE THREAD

**Issue by georgir** [bnoordhuis/node-iconv#144]
This is not a bug in the module but maybe worth noting in the documentation as it seems it may be a common use case.
```
var Iconv = require('iconv').Iconv;
var s='ë';
var enc = new Iconv('utf8', 'latin1');
var dec = new Iconv('latin1', 'utf8');
assert(dec.convert(enc.convert(s))+'' === s); // this one works ok, no intermediate buffer conversion
assert(dec.convert(enc.convert(s)+'')+'' === s); // this one is broken
```
When converting a latin1 buffer to string with the default utf8 encoding, information in it gets corrupted and then the implicit conversion back to buffer to apply iconv on it to utf8 can never work.
This bit me when using the request npm module to fetch latin1 resources, as it applies toString on the buffers it gets by default.

I think it is worth noting in the documentation that for the special case of latin1 to utf8, iconv is not even needed because latin1 is used as the first 256 code points of utf8 and so the built-in 'binary' encoding of buffers is essentially latin1. You just need to call toString('binary') on your buffers instead. Or for my case with the request module, I just had to pass `encoding:'binary'` option to it.

**Comment by bnoordhuis** [comment]
Sorry, the GH notification for this issue got kind of snowed under.  If you want to open a documentation pull request, I'll be happy to review it.  Seems like a worthwhile addition.

**Comment by bnoordhuis** [comment]
I'll go ahead and close the issue.  You're still welcome to follow up with a pull request if you want.
