### ISSUE TITLE
Define LANG variable for transliterations

### ISSUE THREAD

**Issue by DavidBM** [bnoordhuis/node-iconv#145]
I'm working in a server app that needs to transliterate some German characters as `ü ä ë` to ASCII. The correct German transliteration is:  `ue ae oe`, but in English Ubuntu 14.04 this library returns me `"u "a "e`

As example, you can use iconv in terminal whit this:
`echo ü  ä  ë | iconv -f UTF-8 -t ASCII//TRANSLIT//IGNORE`
and it will return:
`u a e`
but if you type before the command
`LANG="de_DE.UTF-8"`
then the same command returns the correct transliterations:
`ue ae oe`

**Is it possible to define a local lang for the transliteration in this library?**
**Or, Is it possible to define the variable LANG in this library?**

**Comment by bnoordhuis** [comment]
I'm afraid the answer is 'no', node-iconv is built without locale support.

Locale support in GNU iconv is not on the same level as glibc's (`iconv --version` will tell you that it's from libc, not GNU iconv.)

You can probably hack node-iconv to link against glibc's iconv without too much hassle.  Untested but I think this is all it takes:
```diff
diff --git a/binding.gyp b/binding.gyp
index f3d0940..cdc4ef6 100644
--- a/binding.gyp
+++ b/binding.gyp
@@ -2,7 +2,6 @@
   'targets': [
     {
       'target_name': 'iconv',
-      'dependencies': ['libiconv'],
       'include_dirs': ['<!(node -e "require(\'nan\')")'],
       'sources': ['src/binding.cc'],
       'cflags': [
@@ -19,45 +18,5 @@
         'WARNING_CFLAGS': ['-Wall', '-Wextra', '-Wno-unused-parameter'],
       },
     },
-
-    {
-      'target_name': 'libiconv',
-      'type': 'static_library',
-      'direct_dependent_settings': {
-        'include_dirs':  ['support'],
-      },
-      'defines': ['ICONV_CONST=const', 'ENABLE_EXTRA=1'],
-      'include_dirs': [
-        'deps/libiconv/srclib',
-        'support',
-      ],
-      'sources': ['deps/libiconv/lib/iconv.c'],
-      'conditions': [
-        ['OS == "win"', {
-          'defines': ['WIN32_NATIVE=1'],
-        }, {
-          'defines': ['HAVE_WORKING_O_NOFOLLOW=1'],
-          'cflags!': ['-W', '-Wall', '-Wextra'],
-        }],
-      ],
-      'msvs_settings': {
-        'VCCLCompilerTool': {
-          'DisableSpecificWarnings': [
-            '4018',  # Signed/unsigned comparison.
-            '4090',  # Const/non-const mismatch.
-            '4244',  # Narrowing cast.
-            '4267',  # Narrowing cast.
-          ],
-        },
-      },
-      'xcode_settings': {
-        'WARNING_CFLAGS!': ['-W', '-Wall', '-Wextra'],
-        'WARNING_CFLAGS': [
-          '-Wno-parentheses-equality',
-          '-Wno-static-in-inline',
-          '-Wno-tautological-compare',
-        ],
-      },
-    }
   ]
 }
```
Hope that helps.

**Comment by DavidBM** [comment]
Oh, thank you. I will try :)

**Comment by DavidBM** [comment]
I have the library working now. 

This are the changes that I made. I hope that it will be useful for you. 

(It's a patch file, I renamed to txt for upload here)
[node-iconv-locale.txt](https://github.com/bnoordhuis/node-iconv/files/113739/node-iconv-locale.txt)
