### ISSUE TITLE
npm ERR! node-gyp rebuild

### ISSUE THREAD

**Issue by mdolzhko** [bnoordhuis/node-iconv#146]
Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild

**Comment by bnoordhuis** [comment]
Can you include the full output, including the output of npm-debug.log?

**Comment by mdolzhko** [comment]
sure, thnx. for remind

[npm-debug.log.zip](https://github.com/bnoordhuis/node-iconv/files/112419/npm-debug.log.zip)

**Comment by mdolzhko** [comment]
i'm trying to do next steps:
https://github.com/plouc/mozaik

1.npm install -g yo gulp generator-mozaik
2.yo mozaik
3.npm install - HERE is error

**Comment by bnoordhuis** [comment]
The log file doesn't really say what went wrong, npm is obnoxious like that.  Can you clone this repo and run `node-gyp rebuild` from the top-level directory?  Please paste the output as a comment.

**Comment by mdolzhko** [comment]
i have done:
1. sudo npm install -g node-gyp
2. node-gyp rebuild

but the error issue is next :

mdolzhko-osx:ta-dashboard apple$ node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.1
gyp info using node@4.2.4 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/apple/WebstormProjects/ta-dashboard/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/apple/.node-gyp/4.2.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/apple/.node-gyp/4.2.4',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/apple/WebstormProjects/ta-dashboard',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /Users/apple/WebstormProjects/ta-dashboard) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/apple/WebstormProjects/ta-dashboard
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok

**Comment by mdolzhko** [comment]
by the way, here is no any Logs...

**Comment by bnoordhuis** [comment]
> sudo npm install -g node-gyp

I'd recommend against installing or updating node-gyp manually.  Use the version that ships with node.

> gyp: binding.gyp not found (cwd: /Users/apple/WebstormProjects/ta-dashboard) while trying to load binding.gyp

By the look of it, you didn't execute `node-gyp rebuild` in the top-level iconv directory.

**Comment by bnoordhuis** [comment]
No follow-up.  I'll go ahead and assume this is working now.  Closing.
