### ISSUE TITLE
Undefined symbol node_module_register

### ISSUE THREAD

**Issue by LestaD** [bnoordhuis/node-iconv#151]
![image](https://cloud.githubusercontent.com/assets/5620073/14314361/68171466-fbff-11e5-8d39-df346b131bab.png)

I install iconv as dependency in the my app.
Then install app on server.

**Comment by bnoordhuis** [comment]
You're trying to load the module with a different version of node.js than what was used to compile it.  `node-gyp rebuild` or `npm rebuild` should fix it; if you're using `npm shrinkwrap`, you'll have to make sure both the local and the remote environment match exactly.

**Comment by LestaD** [comment]
@bnoordhuis oh, thank you. I will try

**Comment by bnoordhuis** [comment]
I'll go ahead and assume this is working now.  Closing.
