### ISSUE TITLE
Node-iconv can't compile success at the version v7.0.0 of node

### ISSUE THREAD

**Issue by hujb2000** [bnoordhuis/node-iconv#155]
[91mnpm WARN optional Skipping failed optional dependency /chokidar/fsevents:
[0m[91mnpm WARN [0m[91mnotsup[0m[91m Not compatible with your operating system or architecture: fsevents@1.0.12
[0m[91mnpm WARN[0m[91m icp@0.0.1 No description
[0m[91mnpm WARN icp@0.0.1 No repository field.
[0m[91mnpm ERR![0m[91m Linux 3.16.0-4-amd64
npm ERR! argv "/root/.envm/versions/easynode/v7.0.1/bin/node" "/root/.envm/versions/easynode/v7.0.1/bin/npm" "install"
[0m[91mnpm ERR! node v7.0.1
[0m[91mnpm ERR! npm  v3.8.6
[0m[91mnpm[0m[91m ERR![0m[91m code ELIFECYCLE

[0m[91mnpm [0m[91mERR![0m[91m iconv@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iconv@2.2.0 install script 'node-gyp rebuild'.
npm ERR![0m[91m Make sure you have the latest version of node.js and npm installed.
npm[0m[91m [0m[91mERR! If you do, this is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR![0m[91m Tell the author that this fails on your system:
[0m[91mnpm ERR![0m[91m     node-gyp rebuild
[0m[91mnpm[0m[91m [0m[91mERR![0m[91m You can get information on how to open an issue for this project with:
npm [0m[91mERR![0m[91m     npm bugs iconv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iconv
[0m[91mnpm [0m[91mERR! There is likely additional logging output above.
[0m[91m
[0m[91mnpm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
[0mThe command '/bin/sh -c source $HOME/.bashrc &&           npm install' returned a non-zero code: 1
now is running as daemon

**Comment by bnoordhuis** [comment]
There is no node v7 yet.  I don't know what this easynode thing is but I suggest you contact its authors.  It's not an issue with node-iconv.
