### ISSUE TITLE
error: Error: Cannot find module '../build/Debug/iconv.node'

### ISSUE THREAD

**Issue by dtaylor7** [bnoordhuis/node-iconv#167]
The latest build is failing for us, see partial stack:

```
Error: Cannot find module '../build/Debug/iconv.node'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (node_modules/iconv/lib/iconv.js:30:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (node_modules/utf8-fdf-generator/lib/generator.js:2:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at node_modules/pdffiller/index.js:12:15
    at Object.<anonymous> (node_modules/pdffiller/index.js:149:2)
```

We have reverted to v2.2.1

**Comment by bnoordhuis** [comment]
Does it fail to build for you?  Can you `cd node_modules/iconv && node-gyp rebuild`?

**Comment by diegomansua** [comment]
Having the same issue here. Doing `node-gyp rebuild` seems to fix it.

**Comment by hsalokor** [comment]
Having the same issue. `node-gyp rebuild` seems to fix it for me too. This seems to have broken in version 2.2.2, since 2.2.1 works without problems.

**Comment by asleepysamurai** [comment]
Can confirm. We have reverted back to 2.2.1 which seems to be working fine.

**Comment by bnoordhuis** [comment]
I suspect an npm issue.  The latest release didn't change anything material; npm simply no longer invokes node-gyp on install, even though the binding.gyp file is there.

**Comment by fiznool** [comment]
FWIW `npm rebuild` worked for me, although this isn't possible for environments like Heroku.

**Comment by silentroach** [comment]
There is no such problem with 2.2.1, so this is a package issue, not npm

**Comment by bnoordhuis** [comment]
@silentroach Okay, if you're so sure, tell me what it is.  The diff between v2.2.1 and and v2.2.2 is a single line.

**Comment by silentroach** [comment]
I think you should compare the package archive content. Ok, will compare in few hours

**Comment by bnoordhuis** [comment]
That's quite literally the first thing I did when I got the first report: download the tarballs and diff them.  It's exactly the diff it's supposed to be.

**Comment by silentroach** [comment]
ha, interesting thing, node-gyp is not triggering to rebuild in postinstall

**Comment by silentroach** [comment]
maybe something is wrong with file rights? it is the only difference I see (excluding code)

    2.2.1:
    -rw-rw-r--   1 silent  staff   1.8K Apr 27  2016 binding.gyp

    npm sill gunzTarPerm extractEntry binding.gyp
    npm sill gunzTarPerm modified mode [ 'binding.gyp', 436, 420 ]

    2.2.2:
    -rw-r--r--   1 silent  staff   1.8K Apr  4 11:24 binding.gyp

    npm sill gunzTarPerm extractEntry binding.gyp

**Comment by bnoordhuis** [comment]
Good suggestion but I don't think that's it.  Running `npm install` from the root of the repo doesn't rebuild for me locally either and updating the permissions makes no difference.

**Comment by bnoordhuis** [comment]
Hm, removing `ignore-scripts=true` from my .npmrc fixes that.  The funny thing is I don't recall having set that.

**Comment by silentroach** [comment]
interesting thing O.o inside install action of npm (trying to debug), pkg.scripts:

2.2.1
 scripts:
      { test: 'tap test/test-*.js',
        install: 'node-gyp rebuild',
        _lifecycleEnv: [Object] }

2.2.2
scripts: { _lifecycleEnv: [Object] },

**Comment by bnoordhuis** [comment]
I noticed the same thing.  The `.scripts` property in `~/.npm/iconv/2.2.[12]/package/package.json` is different; it has an .`install` property with 2.2.1 and it's empty in 2.2.2.

I'm starting to think `ignore-scripts=true` also affects publishes, although I can't find conclusive documentation on that.  I'll grep through npm.

**Comment by bnoordhuis** [comment]
See https://github.com/bnoordhuis/node-buffertools/issues/88, that's indeed what is happening.  Le sigh, I'll file an npm issue.

**Comment by silentroach** [comment]
can't understand it, package.json isn't different in package archives O.o

but it is great that it will be fixed, thank you :)

**Comment by bnoordhuis** [comment]
https://github.com/npm/npm/issues/16243 is the npm issue if you're interested.  Thanks for helping investigate.

**Comment by silentroach** [comment]
Thank you, will watch the issue

**Comment by stefanpl** [comment]
Still had this problem as of today. `npm rebuild` exited with `ok`, but problem persisted. Switching to iconv-lite now.

**Comment by pjangam** [comment]
With 2.3.5 npm install returns success but on npm start I get in browser,
```
./node_modules/iconv/lib/iconv.js
Module not found: Can't resolve '../build/Debug/iconv.node' in '/Users/pramodjangam/code/disruptiveunicorn/htbhf-claim-management-frontend/node_modules/iconv/lib'
```

For 2.2.1, npm install return following error:
```
make: *** [Release/obj.target/iconv/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/pramodjangam/code/frontend/node_modules/iconv
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iconv@2.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iconv@2.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pramodjangam/.npm/_logs/2019-11-05T11_28_06_100Z-debug.log
```

**Comment by bnoordhuis** [comment]
@pjangam What does `ls -lR  /Users/pramodjangam/code/frontend/node_modules/iconv` print?

**Comment by BradleyBrown19** [comment]
I am still getting this error. None of the above fixes have worked for me. Does anyone else have any other solutions?

**Comment by CesarAdan1** [comment]
I was using node-fetch and I am just install it, probably it´s just a lack or a dependency in your project
