### ISSUE TITLE
ks_c_5601-1987 alias

### ISSUE THREAD

**Issue by jorangreef** [bnoordhuis/node-iconv#169]
Outlook 2007 sometimes uses "automatic message encoding" to detect the "optimal" encoding for an outgoing mime message.

This can result in the odd 8-bit character coercing a part to have strange encodings such as "ks_c_5601-1987", even where most of the text is ascii.

I don't know if this is something that iconv should alias, but some MIME decoders pick this up and alias "ks_c_5601-1987" to CP949 (Korean) which is apparently what Microsoft had in mind. Otherwise what would be a mostly-ascii email would decode entirely with asian glyphs.

**Comment by bnoordhuis** [comment]
> and alias "ks_c_5601-1987" to CP949 (Korean)

That seems correct to me and I _think_ node-iconv already does that.  If that isn't working for you, can you post a test script?

**Comment by jorangreef** [comment]
```javascript
var Iconv  = require('iconv').Iconv;

var iconv = new Iconv('ks_c_5601-1987', 'utf-8//TRANSLIT//IGNORE');
var buffer1 = Buffer.from('Reg so dankie');
var buffer2 = iconv.convert(buffer1);

console.log('Buffer 1: ' + JSON.stringify(buffer1.toString('utf-8')));
console.log('Buffer 2: ' + JSON.stringify(buffer2.toString('utf-8')));

if (buffer1.inspect() === buffer2.inspect()) {
  console.log('Pass');
} else {
  throw 'Fail';
}
```

**Comment by jorangreef** [comment]
See: http://docs.activestate.com/activeperl/5.8/lib/Encode/KR.html

I also found a Ruby module which does the same CP949 mapping.

Could you post the links on EUC-KR you found?

**Comment by bnoordhuis** [comment]
Seems I was wrong: IANA considers KS_C_5601-1987 and KS_C_5601-1989 aliases for [ISO-IR-149](https://www.itscj.ipsj.or.jp/iso-ir/149.pdf) and that is what libiconv follows.

> Could you post the links on EUC-KR you found?

Mea culpa.  It was a post on freebsd-users, I think, but I can't find it back.

**Comment by jorangreef** [comment]
Thanks Ben, would you object to adding an alias?

The sample text in the test script I posted was what was provided by Outlook under the KS_C_5601-1987 charset. Decoding it as CP949 works.

The link I provided also provides some more aliases for CP949.

**Comment by jorangreef** [comment]
Some more links:

https://lists.w3.org/Archives/Public/ietf-charsets/2001AprJun/0033.html

https://lists.gnu.org/archive/html/bug-gnu-libiconv/2013-02/msg00003.html

**Comment by bnoordhuis** [comment]
I'm somewhat reluctant to overrule libiconv here, it has an explicit alias in its encodings.def that I expect has been derived directly from IANA's data files.

**Comment by jorangreef** [comment]
Sure, but is KS_C_5601-1987 not a subset of CP949 according to the end of this post:

https://lists.w3.org/Archives/Public/ietf-charsets/2001AprJun/0033.html

**Comment by bnoordhuis** [comment]
To be clear, I wasn't saying you're wrong, just that I don't like the idea of overriding libiconv (and IANA.)

**Comment by jorangreef** [comment]
Thanks Ben, that's fine.

**Comment by bnoordhuis** [comment]
By the way, the reason I thought there was already an alias is because libiconv recognizes "KSC5601" as an alias for CP949 when OSF/1 aliases are enabled (which they currently aren't but I could turn them on if needed.)

**Comment by jorangreef** [comment]
What are OSF/1 aliases? Is there any cost to enabling these or are these sketchy?

**Comment by bnoordhuis** [comment]
OSF/1 is the precursor to X/Open and The Open Group.  There is no real cost to enabling the aliases but as a standard it's been obsolete for more than twenty years so I never saw the point.

That said, AIX aliases are currently disabled as well and those are still relevant in this day and age.  I'll look into it.

**Comment by dumbird** [comment]
We recently encountered an issue that's related to this. An email sent by exchange with an emoji in the subject was encoded with ks_c_5601-1987, and iconv failed to convert it. This is the subject:
Subject: =?ks_c_5601-1987?B?otEgQSBzcGVjaWFsIFByb21vIENvZGUganVzdCBmb3IgeW91Lg==?=
It's supposed to be "Subject: ☞ A special Promo Code just for you."

**Comment by luddd3** [comment]
I have also encountered an email with ks_c_5601-1987 which iconv failed to convert with EUC-KR. Forcing it to CP949 solved the issue.
