### ISSUE TITLE
Build node or node v8 without fpu/vfp!HELP!!!!

### ISSUE THREAD

**Issue by rench** [bnoordhuis/node-iconv#175]
hello bnoordhuis,I see a issue from https://github.com/nodejs/node/issues/7343.
I am a coder on node.js.
I want to run node.js v4.x+ on a router with arm bcm4709 no hard fpu/vfp.
i want make my router to be a smarthome control center.
I try many ways to build node.js  v4.x+ and run this router,
but`illegal instruction`is always show.
i have no idea to do now.so please help me.
i read this issue, and i can not contact to lijunqi .so i think you can help me.
please help me ! thank you!
thank you!
rench.
best wish!

**Comment by bnoordhuis** [comment]
It's already been explained that it's not supported.  Filing issues on an unrelated project is just rude, don't do that again.
