### ISSUE TITLE
EILSEQ is not thrown for ISO-8859-1 conversion

### ISSUE THREAD

**Issue by MartinLoeper** [bnoordhuis/node-iconv#176]
I encountered an issue using this library on Windows-10 64bit with node v8.5.0.  
The following example illustrates how I try to convert an UTF-8 string to ISO-8859-1.  
The string contains characters which are not convertable into ISO-8859-1, so I expect an exception to be thrown (EILSEQ). Am I wrong with my expectation?

```js
let output = "ça va";

// convert to ANSI (ISO-8859-1)
let iconv = new Iconv("UTF-8", "ISO-8859-1");
let convertedOutput: Buffer = iconv.convert(output, "utf8")
```

**Comment by bnoordhuis** [comment]
Are you referring to the 'ç'?  It maps to code point 231 in iso-8859-1.

**Comment by MartinLoeper** [comment]
You are absolutely right. I just wanted to create a test case for EILSEQ being thrown and did not notice that 'ç' is covered by ISO-8859-1.

Thanks for pointing this out! Now everything works as expected by using e.g. 'Ͷ'.
