### ISSUE TITLE
Break Webpack build

### ISSUE THREAD

**Issue by suyuan1203** [bnoordhuis/node-iconv#179]
No sure it's a bug of Webpack or node-iconv

node-iconv source code
```
var bindings;
try {
  bindings = require('../build/Release/iconv.node');
}
catch (e) {
  if (e.code !== 'MODULE_NOT_FOUND') throw e;
  bindings = require('../build/Debug/iconv.node');
}
```

Webpack tries to resolve both '../build/Release/iconv.node' and '../build/Debug/iconv.node', and fails to resolve '../build/Debug/iconv.node', because it doesn't exist.

what's the intension of requiring "Debug" in case requiring "Release" failed?

**Comment by bnoordhuis** [comment]
If you're trying to use iconv in the browser, you can't, it's node.js-only.  Try iconv-lite instead, that might work.

**Comment by suyuan1203** [comment]
@bnoordhuis I'm using iconv in an electron app. And I just found Webpack can ignore '../build/Debug/iconv.node' by adding some configuration. 

Yes, iconv-lite will work.

I will close this issue, but "requiring Debug" still seems strange for me.

**Comment by bnoordhuis** [comment]
Why strange?  `node-gyp build --debug` only builds a debug build, not a release build.

**Comment by suyuan1203** [comment]
@bnoordhuis it does make sense in that way.
