### ISSUE TITLE
Build fails on node 10 because of nan version

### ISSUE THREAD

**Issue by jehy** [bnoordhuis/node-iconv#183]
Error log:

../../nan/nan_maybe_43_inl.h:112:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);

Ca be fixed with bumping nan dependency to latest (2.10.0).

**Comment by bnoordhuis** [comment]
I can update that but note that node-iconv depends on `nan@^2.3.5` (note the caret.)

If npm is selecting an old version, that probably means there's something else in your dependencies that's restricting the version range.

**Comment by jehy** [comment]
Yeah, that's really the case! But if you update nan, then at least compile errors will be in another modules :)
