### ISSUE TITLE
Differences between platforms

### ISSUE THREAD

**Issue by Nakiloe** [bnoordhuis/node-iconv#192]
German eszett (ß) is not transliterate(utf8 to ascii) the same way if we build the module on Mac (=> "ss") or on Linux (=> "s") :/ . Is there a way to prevent these differences ?

**Comment by bnoordhuis** [comment]
That sounds implausible as there is no platform-specific code in node-iconv. Can you post your code?

**Comment by Nakiloe** [comment]
Reducing the code for test, it appears the problem doesn't come from node-iconv, but from the workaround I've made to handle how gnu libiconv process accented letters. Sorry for the false issue :(
