### ISSUE TITLE
Failure on Node.js v12.0.0-pre

### ISSUE THREAD

**Issue by BridgeAR** [bnoordhuis/node-iconv#197]
The input validation for `Buffer.alloc()` is now stricter and it seems like the code passes through `NaN` in some cases. See https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1769/nodes=fedora-latest-x64/testReport/junit/(root)/citgm/iconv_v2_3_2/

**Comment by bnoordhuis** [comment]
Fixed in v2.3.3.

**Comment by BridgeAR** [comment]
@bnoordhuis thanks for the quick fix!
