### ISSUE TITLE
Can't compile on Node.js v12.0.0-pre

### ISSUE THREAD

**Issue by BridgeAR** [bnoordhuis/node-iconv#198]
Due to the recent V8 update (7.4) it's not possible to build `iconv` anymore.

See https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1781/nodes=debian8-64/testReport/junit/(root)/citgm/iconv_v2_3_3/

**Comment by bnoordhuis** [comment]
This will be fixed in v2.3.4 which I'll release as soon as I get to a computer where I can `npm publish`.
