### ISSUE TITLE
Change version for nan to ~2.13.1

### ISSUE THREAD

**Issue by DavidBM** [bnoordhuis/node-iconv#202]
Hi! 

I'm maintaining my own for of this project for allowing full transliterations with native speed. https://github.com/DavidBM/node-iconv 

Recently I ran in a error when `npm i`ing a project. 

It was complaining about `isFirstPass` not existing in the C++ code (nan lib part).

After some time I realized that the problem was how npm was missing information. The version in this package is "^2.13.1" that means "anything between 2.0.0 and 3.0.0". The problem is that this package needs nan greater than "2.13.x". It fails with "2.12.x". 

That should be ok because npm will install the latest available. The problem comes when there is another package that hardcodes a version and npm resolves "nan" package to a lover version than "2.13". (I don't remember what package was, maybe fsevents).

In any case, I just updated the "nan" version of the fork to "~2.13.1" and it worked wonderfully.

You can check the last commit from my fork: https://github.com/DavidBM/node-iconv/commit/e90fccb7d7f8cdf96662279327ebd83777936899

Bests!

**Comment by bnoordhuis** [comment]
Thanks for the report! Fixed in iconv@2.3.5.
