### ISSUE TITLE
cannot open shared object file

### ISSUE THREAD

**Issue by spursy** [bnoordhuis/node-iconv#204]
{
  "errorMessage": "libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory",
  "errorType": "Error",
  "stackTrace": [
    "Module.load (module.js:565:32)",
    "tryModuleLoad (module.js:505:12)",
    "Function.Module._load (module.js:497:3)",
    "Module.require (module.js:596:17)",
    "require (internal/module.js:11:18)",
    "Object.<anonymous> (/var/task/node_modules/iconv/lib/iconv.js:27:14)",
    "Module._compile (module.js:652:30)",
    "Object.Module._extensions..js (module.js:663:10)",
    "Module.load (module.js:565:32)"
  ]
}

**Comment by bnoordhuis** [comment]
How did you install node-iconv? What does `find node_modules/node-iconv` print?

**Comment by bnoordhuis** [comment]
No follow-up, closing.
