### ISSUE TITLE
iconv cannot be used in worker threads

### ISSUE THREAD

**Issue by niftylettuce** [bnoordhuis/node-iconv#211]
Possibly related https://github.com/bnoordhuis/node-iconv/issues/69.

I've tested on both Ubuntu 18.04 + Mac, it seems to happen on all versions of node that support worker threads, and I've also tried rebuilding with node-gyp as well.

Just sharing here, I didn't see this issue posted anywhere

**Comment by bnoordhuis** [comment]
Upgrade to v3.0.0 and it should work. :-)

**Comment by niftylettuce** [comment]
To anyone reading, `iconv@3` release requires `node>=10` whereas `iconv@<3` requires `node@>=0.8`.

Awesome @bnoordhuis - must've missed the email on this 10 days ago 😢

**Comment by niftylettuce** [comment]
I'm going to try it out now @bnoordhuis!  This is AMAZING

**Comment by niftylettuce** [comment]
Seems to work great, thank you @bnoordhuis

**Comment by bnoordhuis** [comment]
My pleasure. :-)
