### ISSUE TITLE
how to change "한글" to euc-kr ?

### ISSUE THREAD

**Issue by muzaffar622** [bnoordhuis/node-iconv#213]
tried all of thinks but not helps. 

var iconv = new Iconv("utf-8", "euc-kr");
var buffer = iconv.convert("하늘");
console.log(buffer.toString("utf-8"));

returns �ϴ�

**Comment by bnoordhuis** [comment]
> `console.log(buffer.toString("utf-8"));`

The `.toString()` operation makes no sense and is why you're seeing garbage. The buffer contains EUC-KR, not UTF-8.
