### ISSUE TITLE
Can't resolve ~~ error while developing an Electron app

### ISSUE THREAD

**Issue by wontheone1** [bnoordhuis/node-iconv#214]
Hi I am using node v14.3.0 and using Electron to use this library. 
I tried the code from Readme and got some errors. (screenshot)
```
// convert from UTF-8 to ISO-8859-1
var Buffer = require("buffer").Buffer;
var Iconv = require("iconv").Iconv;
var assert = require("assert");

var iconv = new Iconv("UTF-8", "ISO-8859-1");
var buffer = iconv.convert("Hello, world!");
var buffer2 = iconv.convert(Buffer.from("Hello, world!"));
```

![Screenshot 2020-06-08 at 0 23 52](https://user-images.githubusercontent.com/11784756/83980439-9577f080-a91e-11ea-8bc0-37dc48c2cc95.png)

**Comment by bnoordhuis** [comment]
That probably means the add-on (the native component) wasn't built or built for the wrong version of Electron. When you `cd /Users/wonseobseo/nb-sent-goods`, what do the following print?

1. `ls -lR node_modules/iconv`
2. `rm -rf node_modules/iconv && npm install iconv && ls -lR node_modules/iconv`
