### ISSUE TITLE
Memory leak when used with byline?

### ISSUE THREAD

**Issue by joshxyzhimself** [bnoordhuis/node-iconv#215]
Hi, I tried using this with byline but I'm getting memory build-up, but without it I'm getting normal size. I wonder what could be causing it

![image](https://user-images.githubusercontent.com/60829711/84980919-e92bda80-b165-11ea-8176-997e18927abb.png)

```
const byline = require('byline');
const Iconv = require('iconv').Iconv;

const iconvStream = new Iconv('latin1', 'utf-8');

const bylineStream = byline.createStream();

fs.createReadStream('./temp/file.csv', { encoding: 'binary' })
    .pipe(iconvStream) // when i comment-out this, I'm getting normal memory usage
    .pipe(bylineStream);
```

**Comment by bnoordhuis** [comment]
Are you saying that when you don't use byline, it works okay? E.g., when you replace the last line with `.pipe(fs.createWriteStream('/dev/null'))`? That makes it an issue with byline, not iconv.

**Comment by joshxyzhimself** [comment]
Closing this for now, I should've looked deeper at that. Thank you.
