### ISSUE TITLE
Upgrade node-gyp to remove python2 dependency

### ISSUE THREAD

**Issue by dbellavista** [bnoordhuis/node-iconv#216]
Hi!

This package still requires `python2` to be correctly installed (since it's required by `node-gyp`). A while ago, `node-gyp` was updated to support `python3`.

Since python2 was deprecated almost a year ago, are you planning on updating the dependency?

**Comment by bnoordhuis** [comment]
node-iconv doesn't depend (directly) on node-gyp, it uses the one that's bundled with npm. You want to update your version of npm, assuming the latest version ships a new enough node-gyp.
