### ISSUE TITLE
Encodings not supported

### ISSUE THREAD

**Issue by RajanHarshit** [bnoordhuis/node-iconv#218]
Hi Team, 
Below is the code where we face conversion issue for given input  **\\x82b382a093fa**
 ```
const Iconv = require("iconv").Iconv;
  let iconv = new Iconv("WIN866","MULE_INTERNAL")
  let res = iconv.convert(Buffer.from('\\x82b382a093fa'));
  res = res.toString("hex");
  console.log("conversion ",`\\x${res}`)
```

Error - Conversion from WIN866 to MULE_INTERNAL is not supported.

Same Error is encountered with the following set of encoding 
1. SHIFT_JIS_2004 to EUC_JIS_2004  with input **\x82b382a093fa**
2. SHIFT_JIS_2004 to JOHAB with input **\x82b382a093fa**
3. EUC_JIS_2004 to SHIFT_JIS_2004 with input **\xa4cfc5fac4ccc7af**
4. LATIN1 to MULE_INTERNAL with input **\x6269e87265**

**Comment by bnoordhuis** [comment]
Closing, no follow-up.
