### ISSUE TITLE
require('iconv') fails

### ISSUE THREAD

**Issue by dsc8x** [bnoordhuis/node-iconv#69]
I installed node-iconv 2.0.6. When i require the module, i'm getting the following error:

```
> require('iconv')
Error: Cannot find module '../build/Debug/iconv.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/epegzz/Development/Projects/NovoBeat/frontend/node_modules/iconv/lib/iconv.js:27:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

The `build/Debug` directory does not exist, only a `build/Release`.

The npm install log can be found here: http://hastebin.com/debufatiji.txt

OS: OSX 10.8.3 
npm: 1.1.59
node: 10.0.1

**Comment by aurium** [comment]
The problem is back. :-(
```
require('iconv')
Error: Cannot find module '../build/Debug/iconv.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/aurium/Projetos/rauzito-bot/node_modules/iconv/lib/iconv.js:29:14)
    ...
```
Nothing of this solved:
* `node-gyp configure build`
* `node-gyp --arch=ia64 rebuild`
* `node-gyp --arch=ia64 --target_arch=ia64 rebuild`
* also trying `node-gyp clean` before
All of this build ok with the same output.

**build**:
```
gyp info it worked if it ends with ok
gyp info using node-gyp@0.12.2
gyp info using node@0.10.38 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/aurium/Projetos/rauzito-bot/node_modules/iconv/build'
  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
  AR(target) Release/obj.target/iconv.a
  COPY Release/iconv.a
  CXX(target) Release/obj.target/iconv/src/binding.o
  SOLINK_MODULE(target) Release/obj.target/iconv.node
  SOLINK_MODULE(target) Release/obj.target/iconv.node: Finished
  COPY Release/iconv.node
make: Leaving directory '/home/aurium/Projetos/rauzito-bot/node_modules/iconv/build'
gyp info ok
```

The iconv installation comes from `npm install iconv`, version 2.1.8

**Comment by aurium** [comment]
```
require('iconv/build/Release/iconv.node')
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
```

**Comment by bnoordhuis** [comment]
@aurium Sounds like you compiled the add-on for the wrong architecture or io.js / node.js version

**Comment by aurium** [comment]
Right, i believe you are right, but... How is this possible? :-)
The NPM did it wrong? `node-gyp configure build` could do it wrong?
You need more information to help with a solution?

This fail is so often, that the team of node-irc put the iconv in a try bloc:
https://github.com/martynsmith/node-irc/blob/e423bcb83aaf2f00b588792c154a2bfe35edc94e/lib/irc.js#L1032-L1044

**Comment by bnoordhuis** [comment]
> node-gyp configure build could do it wrong?

One possible explanation is that you have two different node versions installed (e.g. io.js and node.js), built with one and tried to load it with the other.

> This fail is so often, that the team of node-irc put the iconv in a try bloc:

node-iconv requires a compiler, which not everyone will have, particularly on Windows.  Wrapping the require() makes sense from that perspective.

That try/catch block looks to be dealing with bad / unsupported encoding names as well.  I wouldn't read too much into it.

**Comment by aurium** [comment]
Thanks @bnoordhuis, you let me remember i had one node installed by APT and other locally compiled. The `npm` was provided by the `deb` and the compiled node was default bin linked on `/usr/local/bin`.
Holy crap!

**Comment by Pobux** [comment]
This problem happened to me after I upgraded nodejs version. What I needed to do is to remove `npm remove iconv` and reinstall it `npm` install iconv. This fix it for me.

**Comment by kartsims** [comment]
Got the same issue while running it in a Docker container (`node:6`)... I even removed and rebuilt the container from a clean Dockerfile and still didn't work.

**Comment by nottoseethesun** [comment]
Worked for me once I changed the Travis build env to trusty from the old 12.04.
