### ISSUE TITLE
Compiling in Visual Studio 2013

### ISSUE THREAD

**Issue by Lug16** [bnoordhuis/node-iconv#78]
Hey!
I just want to tell you, I'm running a Win8-64 with just visual studio 2013 Ultimate installed, and when I try to use iconv (npm install iconv) I getting the following error:

> iconv@2.0.7 install C:\Users\Lug\Documents\GitHub\node-iconv
> node-gyp rebuild
> C:\Users\Lug\Documents\GitHub\node-iconv>node "C:\Program Files\nodejs\node_modu
> les\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild
> 
> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.t
> argets(64,5): error MSB8020: The build tools for Visual Studio 2012 (Platform T
> oolset = 'v110') cannot be found. To build using the v110 build tools, please i
> nstall Visual Studio 2012 build tools.  Alternatively, you may upgrade to the c
> urrent Visual Studio tools by selecting the Project menu or right-click the sol
> ution, and then selecting "Upgrade Solution...". [C:\Users\Lug\Documents\GitHub
> \node-iconv\build\iconv.vcxproj]
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
> ed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
> npm\node_modules\node-gyp\lib\build.js:267:23)
> gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:
> 12)
> gyp ERR! System Windows_NT 6.2.9200
> gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
> les\node-gyp\bin\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\Lug\Documents\GitHub\node-iconv
> gyp ERR! node -v v0.10.22
> gyp ERR! node-gyp -v v0.11.0
> gyp ERR! not ok
> 
> npm ERR! iconv@2.0.7 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the iconv@2.0.7 install script.
> npm ERR! This is most likely a problem with the iconv package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls iconv
> npm ERR! There is likely additional logging output above.
> npm ERR! System Windows_NT 6.2.9200
> npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
> ejs\node_modules\npm\bin\npm-cli.js" "install" "--msvs-version=2012"
> npm ERR! cwd C:\Users\Lug\Documents\GitHub\node-iconv
> npm ERR! node -v v0.10.22
> npm ERR! npm -v 1.3.14
> npm ERR! code ELIFECYCLE
> npm ERR!
> npm ERR! Additional logging details can be found in:
> npm ERR!     C:\Users\Lug\Documents\GitHub\node-iconv\npm-debug.log
> npm ERR! not ok code 0

Hope you can check that...

Thanks for all

**Comment by adetunji** [comment]
@bnoordhuis works like a gem (no pun)
